apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 3
  selector:
    matchLabels:
       app: www
  template: 
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.3
        ports:
        - containerPort: 80