apiVersion: v1
kind: Pod
metadata:
  name: api
spec:
  containers:
  - name: message
    image: lucj/messages:1.0
    env: 
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongo
          key: mongo_url